---
date: '2024-01-21T04:56:47+07:00'
draft: false
title: 'Neovim Sebagai IDE'
tags: [Tech, Tutorial, neovim]
description: 'Neovim Merupakan sebuah text editor yang minimalis. Secara default Neovim tidak memiliki banyak fitur. Pada Tutorial ini saya akan menunjukkan cara instalasi agar Neovim memiliki fitur-fitur seperti text editor lain.'
---
{{< img src="/dashboard.png" title="Neovim - NvChad" alt="Neovim" >}}

Neovim Merupakan sebuah text editor yang minimalis. Secara default Neovim tidak memiliki banyak fitur seperti IDE yang biasanya seperti Vscode, Atom, dll. Untuk menambahkan fitur-fitur pada Neovim diperlukan effort yang lebih seperti instalasi plugin, konfigurasi autocomplete, dll.

Nah sekarang mulai ada berbagai macam autogenerated neovim configuration, dimana kita tidak perlu susah susah untuk melakukan konfigurasi. Saat ini contohnya ada lazyvim, astrovim, dan masih banyak lagi. Pada blog post ini saya akan menjelaskan cara instalasi dari **NvChad** dan untuk distro yang saya gunakan adalah Ubuntu. Tetapi kalian juga bisa menginstall pada distro lainnya.

Berikut cara instalasinya:
1. Install Neovim
```shell
sudo apt install neovim
```
2. Cek versi Neovim
```shell
nvim --version
```
3. Tambahkan PPA Neovim Unstable **(Jika version < 0.10.0)**
```shell
sudo add-apt-repository ppa:neovim-ppa/unstable
```
4. Install NvChad
```shell
git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim
```
## Preview
{{< img src="/preview.png" title="Preview NvChad" alt="Preview Image" >}}

Selamat!! Neovim kalian akan menjadi IDE seperti Vscode 👍😁👍. Untuk shortcut/keybinding dari NvChad dapat dilihat pada [Link ini](https://nvchad.com/docs/features "NvChad") atau ketikkan **"Spasi+ch"** pada saat Normal mode.


****Direkomendasikan sebelum menggunakan vim/neovim kalian harus biasa menggunakan vim binding.***
